"""Optional, default-disabled DAZ exact-synthetic supervision lane."""

from .backup import (
    TierABackupPolicy,
    create_tier_a_backup,
    load_tier_a_backup_policy,
    plan_tier_a_backup,
    plan_tier_a_restore_test,
    restore_tier_a_test,
    verify_tier_a_backup,
)
from .control import (
    DazControlError,
    DazErrorCode,
    RegisteredRootResolver,
    append_event,
    build_event,
    initialize_daz_root,
    initialize_state_database,
    inspect_state_database,
    load_control_configuration,
    read_control_state,
    result_envelope,
    set_control_state,
)
from .lineage import (
    ingest_adapted_scene,
    query_descendants,
    register_downstream_artifact,
    revoke_lineage,
)
from .monitoring import (
    AlertPolicy,
    build_daily_report,
    build_dashboard,
    collect_monitoring_snapshot,
    evaluate_alerts,
    load_alert_policy,
    validate_monitoring_snapshot,
)
from .policy import (
    DazAcquisitionCapacity,
    DazConfiguration,
    DazPolicyError,
    daz_foundation_doctor,
    inspect_acquisition_queue,
    load_typed_daz_configuration,
    validate_daz_configuration,
    validate_synthetic_authority,
    validate_synthetic_share,
)
from .protocol import DazJobFiles, prepare_job_files, read_terminal_result, stage_recipe
from .recovery import RecoveryPolicy, evaluate_recovery_matrix, load_recovery_policy
from .runtime import (
    DazRuntimePaths,
    DazRuntimeProfile,
    deploy_script_bundle,
    load_daz_runtime_profile,
    script_bundle_manifest,
)
from .scheduler import finish_lease, lease_next_job, scheduler_status
from .source_guard import PROHIBITED_EXTENSIONS, find_prohibited_source_assets
from .storage import (
    GIB,
    PROTECTED_RETENTION_CLASSES,
    RETENTION_CLASSES,
    RetentionClassPolicy,
    RetentionPolicy,
    apply_capacity_control,
    apply_retention_plan,
    build_retention_plan,
    load_retention_policy,
    register_retention_artifact,
    required_reservation_bytes,
    reserve_job_storage,
    storage_capacity_decision,
)
from .worker import (
    DazWorkerOutcome,
    WindowObservation,
    build_daz_command,
    detect_daz_dialog,
    operation_timeout,
    run_daz_job,
    running_daz_processes,
)

__all__ = [
    "DazConfiguration",
    "DazAcquisitionCapacity",
    "DazControlError",
    "DazErrorCode",
    "DazPolicyError",
    "DazJobFiles",
    "DazRuntimePaths",
    "DazRuntimeProfile",
    "DazWorkerOutcome",
    "GIB",
    "AlertPolicy",
    "PROTECTED_RETENTION_CLASSES",
    "RETENTION_CLASSES",
    "RegisteredRootResolver",
    "RecoveryPolicy",
    "RetentionClassPolicy",
    "RetentionPolicy",
    "TierABackupPolicy",
    "WindowObservation",
    "PROHIBITED_EXTENSIONS",
    "append_event",
    "apply_capacity_control",
    "apply_retention_plan",
    "build_event",
    "build_daily_report",
    "build_dashboard",
    "build_daz_command",
    "build_retention_plan",
    "daz_foundation_doctor",
    "collect_monitoring_snapshot",
    "create_tier_a_backup",
    "deploy_script_bundle",
    "detect_daz_dialog",
    "find_prohibited_source_assets",
    "finish_lease",
    "evaluate_alerts",
    "evaluate_recovery_matrix",
    "inspect_acquisition_queue",
    "initialize_daz_root",
    "initialize_state_database",
    "ingest_adapted_scene",
    "inspect_state_database",
    "load_control_configuration",
    "load_alert_policy",
    "load_tier_a_backup_policy",
    "plan_tier_a_backup",
    "plan_tier_a_restore_test",
    "load_retention_policy",
    "load_recovery_policy",
    "load_daz_runtime_profile",
    "load_typed_daz_configuration",
    "lease_next_job",
    "read_control_state",
    "query_descendants",
    "register_downstream_artifact",
    "register_retention_artifact",
    "operation_timeout",
    "prepare_job_files",
    "read_terminal_result",
    "running_daz_processes",
    "result_envelope",
    "restore_tier_a_test",
    "required_reservation_bytes",
    "reserve_job_storage",
    "scheduler_status",
    "set_control_state",
    "revoke_lineage",
    "script_bundle_manifest",
    "stage_recipe",
    "storage_capacity_decision",
    "run_daz_job",
    "validate_daz_configuration",
    "validate_monitoring_snapshot",
    "verify_tier_a_backup",
    "validate_synthetic_authority",
    "validate_synthetic_share",
]
