"""Optional, default-disabled DAZ exact-synthetic supervision lane."""

from .control import (
    DazControlError,
    DazErrorCode,
    RegisteredRootResolver,
    append_event,
    build_event,
    initialize_daz_root,
    initialize_state_database,
    inspect_state_database,
    load_control_configuration,
    read_control_state,
    result_envelope,
    set_control_state,
)
from .lineage import (
    ingest_adapted_scene,
    query_descendants,
    register_downstream_artifact,
    revoke_lineage,
)
from .policy import (
    DazAcquisitionCapacity,
    DazConfiguration,
    DazPolicyError,
    daz_foundation_doctor,
    inspect_acquisition_queue,
    load_typed_daz_configuration,
    validate_daz_configuration,
    validate_synthetic_authority,
    validate_synthetic_share,
)
from .protocol import DazJobFiles, prepare_job_files, read_terminal_result, stage_recipe
from .runtime import (
    DazRuntimePaths,
    DazRuntimeProfile,
    deploy_script_bundle,
    load_daz_runtime_profile,
    script_bundle_manifest,
)
from .scheduler import finish_lease, lease_next_job, scheduler_status
from .source_guard import PROHIBITED_EXTENSIONS, find_prohibited_source_assets
from .worker import (
    DazWorkerOutcome,
    WindowObservation,
    build_daz_command,
    detect_daz_dialog,
    operation_timeout,
    run_daz_job,
    running_daz_processes,
)

__all__ = [
    "DazConfiguration",
    "DazAcquisitionCapacity",
    "DazControlError",
    "DazErrorCode",
    "DazPolicyError",
    "DazJobFiles",
    "DazRuntimePaths",
    "DazRuntimeProfile",
    "DazWorkerOutcome",
    "RegisteredRootResolver",
    "WindowObservation",
    "PROHIBITED_EXTENSIONS",
    "append_event",
    "build_event",
    "build_daz_command",
    "daz_foundation_doctor",
    "deploy_script_bundle",
    "detect_daz_dialog",
    "find_prohibited_source_assets",
    "finish_lease",
    "inspect_acquisition_queue",
    "initialize_daz_root",
    "initialize_state_database",
    "ingest_adapted_scene",
    "inspect_state_database",
    "load_control_configuration",
    "load_daz_runtime_profile",
    "load_typed_daz_configuration",
    "lease_next_job",
    "read_control_state",
    "query_descendants",
    "register_downstream_artifact",
    "operation_timeout",
    "prepare_job_files",
    "read_terminal_result",
    "running_daz_processes",
    "result_envelope",
    "scheduler_status",
    "set_control_state",
    "revoke_lineage",
    "script_bundle_manifest",
    "stage_recipe",
    "run_daz_job",
    "validate_daz_configuration",
    "validate_synthetic_authority",
    "validate_synthetic_share",
]
