"""Generate or drift-check the human-readable v1/v2 ontology reference."""

from __future__ import annotations

import argparse
from pathlib import Path

from maskfactory.ontology import load_ontology

ROOT = Path(__file__).resolve().parents[1]
V1_ONTOLOGY = ROOT / "configs" / "ontology.yaml"
V2_ONTOLOGY = ROOT / "configs" / "ontology_v2.yaml"
DEFAULT_OUTPUT = ROOT / "Plan" / "OntologyV2" / "VERSIONED_REFERENCE.md"


def _indexed_parts(path: Path) -> tuple[tuple[int, str], ...]:
    ontology = load_ontology(path)
    values = tuple(
        sorted(
            (int(label.id), label.name)
            for label in ontology.labels_for_map("part")
            if label.id is not None
        )
    )
    ids = tuple(label_id for label_id, _ in values)
    if ids != tuple(range(len(values))):
        raise ValueError(f"PART IDs are not contiguous in {path}: {ids}")
    return values


def render_reference() -> str:
    """Render the exact checked-in version matrix from generated ontologies."""
    v1 = _indexed_parts(V1_ONTOLOGY)
    v2 = _indexed_parts(V2_ONTOLOGY)
    if len(v1) != 56 or len(v2) != 66 or v2[: len(v1)] != v1:
        raise ValueError("body_parts_v2 is not an exact append-only 56-to-65 extension")
    additions = v2[len(v1) :]
    lines = [
        "<!-- Generated by tools/generate_ontology_version_reference.py; do not hand-edit. -->",
        "# MaskFactory Ontology Version Reference",
        "",
        "| Contract | Active production v1 | Approved, inactive v2 |",
        "|---|---|---|",
        "| Version | `body_parts_v1` | `body_parts_v2` |",
        "| PART IDs/logits including background | `0..55` / 56 | `0..65` / 66 |",
        "| Ontology | `configs/ontology.yaml` | `configs/ontology_v2.yaml` |",
        "| Manifest schema | `manifest.schema.json` | `manifest_v2.schema.json` |",
        "| Derived/viz config | `derived.yaml`, `viz.yaml` | `derived_v2.yaml`, `viz_v2.yaml` |",
        "| CVAT project | `MaskFactory_body_parts_v1` | separate `MaskFactory_body_parts_v2_pilot` |",
        "| Training authority | approved v1 packages | fully reviewed v2 packages only |",
        "| Serving | active v1 champions | blocked until every doc-18 activation gate passes |",
        "",
        "The number of PART logits already includes background ID 0. The historical phrase",
        '"57 classes" is invalid. V1 remains the runtime default until the activation checklist',
        "is complete; generating or reviewing v2 artifacts does not activate them.",
        "",
        "## Appended v2 atomics",
        "",
        "| ID | Canonical label |",
        "|---:|---|",
    ]
    lines.extend(f"| {label_id} | `{name}` |" for label_id, name in additions)
    lines.extend(
        [
            "",
            "## Version-aware operator commands",
            "",
            "```powershell",
            "maskfactory draft <image>  # active v1 D1 path: 56 PART masks",
            "maskfactory dataset build --name bodyparts --ontology body_parts_v1",
            "maskfactory dataset build --name bodyparts --ontology body_parts_v2  # gated; 200 reviewed v2 packages required",
            "maskfactory verify-package --root <restored-packages>  # dispatches by manifest ontology",
            "python tools/cvat_v2.py init  # separate inactive-v2 pilot project",
            "python tools/generate_ontology_version_reference.py --check",
            "```",
            "",
            "## Authority",
            "",
            "- Active v1 semantics: documents 00–17 and `configs/ontology.yaml`.",
            "- V2 delta, states, SOP, QA, migration, and activation: document 18.",
            "- Executable gate state: `Plan/OntologyV2/IMPLEMENTATION_CHECKLIST.md`.",
            "- Production activation must update the runtime default, champions, workflows, docs,",
            "  tracker, and this generated reference in one verified change.",
            "",
        ]
    )
    return "\n".join(lines)


def write_reference(path: Path = DEFAULT_OUTPUT) -> Path:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_reference(), encoding="utf-8")
    return output


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the checked-in file drifted")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)
    rendered = render_reference()
    if args.check:
        if args.output.is_file() and args.output.read_text(encoding="utf-8") == rendered:
            print("ontology version reference current")
            return 0
        print("ontology version reference drift")
        return 1
    print(write_reference(args.output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
